### ISSUE TITLE
I cannot find Crucible4IDEA.zip with IDEA plug-in

### ISSUE THREAD

**Issue by andkirby** [ktisha/Crucible4IDEA#64]
I cannot find Crucible4IDEA.zip with IDEA plug-in.
Where is it?...

**Comment by ktisha** [comment]
Hi andkirby, 
it's now available through [jetbrains plugin repository] (https://plugins.jetbrains.com/plugin/7223?pr=idea)
and could be installed from IDE in Settings->Plugins->Browse Repositories->Code Review for IntelliJ IDEA

**Comment by andkirby** [comment]
Hi ktisha,
Thanks for the answer! I'll check this out.
